# Generated by Django 4.2.23 on 2025-12-14 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_category_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='category',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='slug',
        ),
        migrations.AddField(
            model_name='quiz',
            name='difficulty_label',
            field=models.CharField(default='Medium', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='overview',
            field=models.TextField(blank=True, help_text='Short description shown before starting the quiz'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rules',
            field=models.TextField(blank=True, help_text='Quiz rules shown before starting'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topics_covered',
            field=models.TextField(blank=True, help_text='One topic per line'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
