# Generated by Django 4.2.23 on 2025-12-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_quiz_category_remove_quiz_slug_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='difficulty_label',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='overview',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='rules',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='topics_covered',
        ),
        migrations.AddField(
            model_name='quiz',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='myapp.category'),
        ),
    ]
