# Generated by Django 4.2.23 on 2025-12-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_quiz_difficulty_label_remove_quiz_overview_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='difficulty_label',
            field=models.CharField(blank=True, help_text='Easy / Medium / Hard / Mixed', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='overview',
            field=models.TextField(blank=True, help_text='Short overview shown on quiz detail page'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='rules',
            field=models.TextField(blank=True, help_text='Quiz rules (time, attempts, marking)'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='topics_covered',
            field=models.TextField(blank=True, help_text='Comma separated topics'),
        ),
    ]
